name: Deploy automation

on:
  issues:
    types: opened

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "New Issue"

  setup:
    if: contains(github.event.issue.labels.*.name, 'deploy-automation')
    name: Setup
    needs: [ welcome ]
    outputs:
      branches: ${{ steps.branches.outputs.values }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deploy
        run: echo "Setup deploy"

      - name: Get action link
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Action link [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Atualizar branches
        run: |
          git fetch --all

      - name: Obtém a branch a ser mergeada
        id: branches
        run: |
          set +e
          values=`python3 .github/support/deploy-homolog.py "parse-branches" "${{ github.event.issue.body }}"`
          echo $values
          echo "values<<EOF" >> $GITHUB_OUTPUT
          echo "$values" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Rebase homolog
        run: |
          set +e
          git checkout develop
          git checkout homolog
          git rebase develop

      - name: Rebase branch
        run: |
          set +e
          git checkout develop
          git checkout ${{ steps.branches.outputs.values }}
          git rebase develop

      - name: Merge branch
        run: |
          set +e
          git config --global user.email "robot@github.com"
          git config --global user.name "Homolog Robot"
          git checkout homolog
          git merge ${{ steps.branches.outputs.values }}

      - name: Push branch
        run: |
          set +e
          git push origin homolog

      # TODO: Testar se sempre está sendo executado!
      - name: Close issue
        if: (failure() || success()) && !cancelled()
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            ## Finish :rocket:
            Branches updated: ${{ steps.branches.outputs.values }}
            Automation completed.
